### ISSUE TITLE
Add a hover on the navigation bar items

### ISSUE THREAD

**Issue by srijanishere** [joomla/foundation.joomla.org#7]
A simple CSS could be added when the cursor is placed on the navigation bar icons for a better outlook. If the suggestion is accepted I would want to work on it.

**Comment by skpandey885** [comment]
Hello Sir! Can I work On this Issue?

**Comment by Palaksharma23** [comment]
Hello I would love to work on this issue , Can you please assign it to me .

**Comment by conconnl** [comment]
Everybody can create a PR on the code available in this repository and with that provide improvements.

**Comment by srijanishere** [comment]
@conconnl I've already created a PR on this issue.

**Comment by conconnl** [comment]
#8
@JazParkyn

**Comment by Palaksharma23** [comment]
Can somebody please tell me how to set this up in my local computer

**Comment by conconnl** [comment]
That is not possible and the PR has already been created.

**Comment by Palaksharma23** [comment]
Okay @conconnl

**Comment by Palaksharma23** [comment]
But I am also working on this issue and i will submit my pr till tomorrow morning .

**Comment by conconnl** [comment]
That is fine, also check #8 created by someone else. 
I'm sure when @JazParkyn has time again, she will check and merges it.

**Comment by JazParkyn** [comment]
Changes requested on the PR #8

**Comment by Palaksharma23** [comment]
@conconnl @JazParkyn  please once review my pr

**Comment by Palaksharma23** [comment]
@JazParkyn @conconnl i have added the changes on active and hover state

**Comment by Parna2000** [comment]
Is this issue still open? Can i work on it @conconnl @JazParkyn ?

**Comment by deepak-yadav123** [comment]
Hello Sir, I am Fascinated to Work on this will you please assign if possible

**Comment by Arpitgupta1014** [comment]
Hello sir, Can I work on this issue.

**Comment by Puja-Mangale** [comment]
@conconnl Hello Sir, I want to work on this issue, is this still open?

**Comment by konti-aditi** [comment]
Hello @conconnl ,I would like to work on this issue please assign me if possible
